[relaychain]
default_image = "docker.io/parity/pezkuwi:latest"
default_command = "pezkuwi"
default_args = ["-lparachain=debug"]

chain = "pezkuwichain-local"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 100
chain = "asset-hub-pezkuwi-local"

[parachains.collator]
name = "collator01"
image = "docker.io/parity/pezkuwi-parachain:latest"
ws_port = 42069
command = "pezkuwi-parachain"
args = ["-lparachain=debug"]
